---

- name: assertions
  assert:
    that:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version in ["6"]

- name: package for webmin is present
  package:
    name: webmin
    state: present

- name: service for webmin ist started
  service:
    name: webmin
    state: started
    enabled: true
